### ISSUE TITLE
Fix proxy_pass location / for docker nginx

### ISSUE THREAD

**Issue by cenobitz** [bookwyrm-social/documentation#102]
https://github.com/bookwyrm-social/documentation/blob/main/content/running_bookwyrm/reverse-proxy.md
in docker-compose.yml is:

`
version: '3'

services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
       - "8001:8001"
`
so in nginx should be not 8000 but:
`
    location / {
        proxy_pass http://localhost:8001;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
    }
`

**Comment by Sebastix** [comment]
When I do that, I got a 502 error from nginx

```*2665 connect() failed (111: Connection refused) while connecting to upstream, client: 92.70.xxx.xxx, server: books.sebastix.social, request: "GET /setup HTTP/1.1", upstream: "http://127.0.0.1:8001/setup"```

**Comment by cenobitz** [comment]
docker-compose.yml

```
version: '3'

services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
       - "8001:8001"
    depends_on:
      - web
    networks:
      - main
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/app/static
      - media_volume:/app/images
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - main
  web:
    build: .
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/images
    depends_on:
      - db
      - celery_worker
      - redis_activity
    networks:
      - main
    ports:
      - "8000"
```
in bookwyrm /nginx/default.conf

```
include /etc/nginx/conf.d/server_config;

upstream web {
    server web:8000;
}
```
server {
    if ($host = book.yourdomain.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    server_name book.yourdomain.com;

    listen [::]:80;
    listen 80;
    add_header Strict-Transport-Security "max-age=31536000;includeSubDomains" always;
    location / { return 301 https://$host$request_uri; }


}

server {
    listen [::]:443 ssl http2;
    listen 443 ssl http2;

    # SSL code
    ssl_certificate /etc/letsencrypt/live/book.yourdomain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/book.yourdomain.com/privkey.pem; # managed by Certbot

    server_name book.yourdomain.com;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    location / {
        proxy_pass http://localhost:8001;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
    }

    location /images/ {
        proxy_pass http://localhost:8001;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
    }

    location /static/ {
        proxy_pass http://localhost:8001;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
    }

}
```

This is working for me

**Comment by hughrun** [comment]
The docs could be clearer, but there is not an error with the ports.

The example from @cenobitz is for the **development** server (`main`) branch. `production` [serves the primary website from the `web` service](https://github.com/bookwyrm-social/bookwyrm/blob/production/docker-compose.yml), which uses port `8000`:

```
  web:
    build: .
    env_file: .env
    command: gunicorn bookwyrm.wsgi:application --threads=8 --bind 0.0.0.0:8000
    ports:
      - "8000"
```

`nginx` serves asset files from `8001`.

There are discussions about moving away from the main/production branch arrangement partially because it's confusing like this.
